export function createDodgeState(profile, ability = null) {
  const gradient = profile?.dodge?.gradient ?? {};
  const distanceMaxMeters = positive(gradient.distanceMaxMeters, 0.56);
  return {
    classification: 'shared_collision_safe_dodge_state_v0',
    profileId: profile?.id ?? 'unknown_locomotion_profile',
    enabled: profile?.dodge?.enabled === true,
    active: false,
    recovering: false,
    cost: positive(ability?.staminaCost, profile?.dodge?.cost ?? 0),
    baseDistance: positive(profile?.dodge?.distance, 0),
    distance: positive(profile?.dodge?.distance, 0),
    duration: Math.max(0.01, finite(profile?.dodge?.duration, 0.01)),
    baseCooldown: positive(profile?.dodge?.cooldown, 0),
    cooldown: positive(profile?.dodge?.cooldown, 0),
    cooldownRemaining: 0, directionX: 0, directionY: 0,
    elapsed: 0, phase: 0,
    visualRecoveryDuration: positive(profile?.dodge?.visualRecoveryDuration, 0),
    visualRecoveryStartPhase: clamp01(finite(profile?.dodge?.visualRecoveryStartPhase, 1)),
    recoveryElapsed: 0, recoveryProgress: 0, recoveryStartPhase: 1,
    landingHoldRemaining: 0, chainLandingHoldSeconds: 0.06,
    distanceApplied: 0, blocked: false,
    gradientEnabled: gradient.enabled === true,
    gradientCurve: gradient.curve ?? 'smoothstep',
    fullEffectEnergy01: Math.max(0.001, clamp01(finite(gradient.fullEffectEnergy01, 0.4))),
    minEffectiveness: clamp01(finite(gradient.minEffectiveness, 0.5)),
    distanceMinMeters: positive(gradient.distanceMinMeters, distanceMaxMeters * 0.5),
    distanceMaxMeters,
    apexMinMeters: positive(gradient.apexMinMeters, 0.06),
    apexMaxMeters: positive(gradient.apexMaxMeters, 0.12),
    landingCompressionLowEnergyMeters: positive(gradient.landingCompressionLowEnergyMeters, 0.09),
    landingCompressionFullEnergyMeters: positive(gradient.landingCompressionFullEnergyMeters, 0.06),
    cooldownLowEnergySeconds: positive(gradient.cooldownLowEnergySeconds, 0.75),
    cooldownFullEnergySeconds: positive(gradient.cooldownFullEnergySeconds, profile?.dodge?.cooldown ?? 0.55),
    inputBufferSeconds: positive(profile?.dodge?.inputBufferSeconds, 0.12),
    interruptionBlendSeconds: positive(profile?.dodge?.interruptionBlendSeconds, 0.08),
    mode: 'full', energy01: 1, effectiveness: 1, gradient01: 1,
    distanceRequestedMeters: distanceMaxMeters,
    apexHeightMeters: positive(gradient.apexMaxMeters, 0.12),
    landingCompressionMeters: positive(gradient.landingCompressionFullEnergyMeters, 0.06),
    cooldownApplied: positive(profile?.dodge?.cooldown, 0),
    staminaSpent: 0, followupsEnabled: true,
    buffered: false, bufferRemaining: 0, bufferedMode: null,
    bufferedDirectionX: 0, bufferedDirectionY: 0, bufferedEnergy01: 0,
    bufferedEffectiveness: 0, bufferedGradient01: 0, bufferedDistance: 0,
    bufferedDistanceMeters: 0, bufferedApexHeightMeters: 0,
    bufferedLandingCompressionMeters: 0, bufferedCooldown: 0,
    bufferedReservedCost: 0, bufferedFollowupsEnabled: false,
    bufferedStaminaBefore: 0, bufferedRecoveryTimerBefore: 0, bufferedExhaustedBefore: false,
    aiStyle: profile?.dodge?.aiStyle ?? null,
    aiTriggerRange: positive(profile?.dodge?.aiTriggerRange, 0),
    count: 0, chainIndex: 0, queuedChain: false,
    queuedDirectionX: 0, queuedDirectionY: 0, reservedChainCost: 0,
    queuedMode: null, queuedEnergy01: 0, queuedEffectiveness: 0, queuedGradient01: 0,
    queuedDistance: 0, queuedDistanceMeters: 0, queuedApexHeightMeters: 0,
    queuedLandingCompressionMeters: 0, queuedCooldown: 0, queuedFollowupsEnabled: false,
    queuedStaminaBefore: 0, queuedRecoveryTimerBefore: 0, queuedExhaustedBefore: false,
    committedBranch: null, lastReason: null, lastDeniedReason: null,
    lastRequestReceipt: null
  };
}

function positive(value, fallback) { return Math.max(0, finite(value, fallback)); }
function finite(value, fallback) { const numeric = Number(value); return Number.isFinite(numeric) ? numeric : fallback; }
function clamp01(value) { return Math.max(0, Math.min(1, value)); }
