import { RENDER_BUDGETS } from '../data/renderBudgets.js';

export function createRenderLayerState() {
  return {
    renderer: {
      classification: 'derived_projection_renderer_backend_stats',
      preferredBackend: RENDER_BUDGETS.renderer.preferredBackend,
      candidateBackend: RENDER_BUDGETS.renderer.candidateBackend,
      activeBackend: 'uninitialized',
      backendStatus: 'pending',
      fallbackReason: null,
      initializationError: null,
      webglContext: 'uninitialized',
      textureUploads: 0,
      fullSceneTextureUploadActive: false,
      rendererMode: 'pending',
      legacyCompositeActive: false,
      preferenceSource: 'budget_default',
      requestedBackend: RENDER_BUDGETS.renderer.preferredBackend,
      activationPolicy: RENDER_BUDGETS.renderer.activationPolicy,
      migrationPolicy: RENDER_BUDGETS.renderer.migrationPolicy,
      sceneLayerPolicy: RENDER_BUDGETS.renderer.sceneLayerPolicy,
      unsupportedRendererPolicy: RENDER_BUDGETS.renderer.unsupportedRendererPolicy,
      canvas2dRuntimeAvailable: false,
      hiddenCanvasRenderLoopActive: false,
      layerOrder: [],
      webglLayerOrder: [],
      layerStats: {},
      webglMigrationCoverageStatus: RENDER_BUDGETS.renderer.migrationCoverageStatus,
      webglDarknessLayerActive: false,
      webglLightCount: 0,
      webglDarknessRenderMs: 0,
      webglDarknessMode: null,
      webglLightingProfileId: null,
      webglLightingInfluenceCount: 0,
      webglFlickeringLightCount: 0,
      webglLightSpaceCullingActive: false,
      webglLightSpaceCulledCount: 0,
      webglLightSpaceMode: null,
      webglOcclusionShadowMode: null,
      webglOcclusionShadowRegions: 0,
      webglOcclusionShadowRenderable: false,
      webglShadowShaderMode: null,
      webglShadowCompositeMode: null,
      webglShadowBlendStrength: 0,
      webglShadowFieldEdgeSoftness: 0,
      webglShadowFieldPenumbraGamma: 0,
      webglShadowFieldTailFloor: 0,
      webglShadowLightHaloBlendScale: 0,
      webglShadowPenumbraTriangleCount: 0,
      webglShadowCoreTriangleCount: 0,
      webglShadowContactTriangleCount: 0,
      webglShadowSegmentCount: 0,
      webglShadowFieldPacketCount: 0,
      webglShadowFieldSampleCount: 0,
      webglShadowFieldPrimitiveCount: 0,
      webglShadowSilhouettePrimitiveCount: 0,
      webglShadowShaderPacketCount: 0,
      webglShadowShaderPrimitiveCount: 0,
      webglSceneryLayerActive: false,
      webglSceneryMode: null,
      webglScenerySourceCount: 0,
      webglSceneryPrimitiveCount: 0,
      webglSceneryRenderMs: 0,
      webglWorldDepthLayerActive: false,
      webglWorldDepthMode: null,
      webglWorldDepthItemCount: 0,
      webglDecalLayerActive: false,
      webglDecalMode: null,
      webglDecalSourceCount: 0,
      webglDecalPrimitiveCount: 0,
      webglDecalRenderMs: 0,
      webglEffectLayerActive: false,
      webglEffectMode: null,
      webglEffectSourceCount: 0,
      webglEffectPrimitiveCount: 0,
      webglEffectRenderMs: 0,
      webglParticleCount: 0,
      webglParticlePrimitiveCount: 0,
      webglParticleBudgetMax: 0,
      webglHudLayerActive: false,
      webglHudLineCount: 0,
      webglHudRenderMs: 0,
      webglHudMode: null,
      webglPlayerWyvernSilhouetteActive: false,
      webglPlayerWyvernPartCount: 0,
      webglRaiderHumanoidSilhouetteActive: false,
      webglRaiderHumanoidPartCount: 0,
      webglRaiderHumanoidTorchSocketCount: 0,
      webglRaiderHumanoidSpearSocketCount: 0,
      webglRaiderHumanoidMode: null,
      webglPredatorSilhouetteActive: false,
      webglPredatorPartCount: 0,
      webglPredatorMode: null,
      webglActorRenderMs: 0,
      webglActorMode: null,
      webglActorShadowLodMode: null,
      webglActorShadowLodCount: 0,
      webglActorShadowLodPrimitiveCount: 0,
      webglPostProcessActive: false,
      webglPostProcessMode: null,
      webglPostProcessRenderMs: 0,
      webglPostProcessPassCount: 0,
      webglPostProcessRenderTargetActive: false,
      webglFogSmokeLayerActive: false,
      webglFogSmokeMode: null,
      webglFogSmokeSourceCount: 0,
      webglFogSmokePrimitiveCount: 0,
      webglFogSmokeRenderMs: 0,
      backendPresentMs: 0,
      totalRenderMs: 0
    },
    terrain: {
      classification: 'derived_projection_terrain_render_stats',
      cachePolicy: RENDER_BUDGETS.renderer.terrainCachePolicy,
      cacheMode: 'pending',
      mapKey: '',
      cacheRebuilds: 0,
      fullMapTiles: 0,
      visibleTilesConsidered: 0,
      visibleTilesDrawn: 0,
      visibleTileColumns: 0,
      visibleTileRows: 0
    },
    frameTiming: {
      classification: 'derived_projection_render_phase_timing_stats',
      policy: 'renderer_phase_timing_ms',
      frame: 0,
      totalMs: 0,
      backendBeginMs: 0,
      lightSpaceMs: 0,
      terrainMs: 0,
      worldDetailsMs: 0,
      lightingMs: 0,
      smokeMs: 0,
      postProcessMs: 0,
      hudMs: 0,
      backendPresentMs: 0
    },
    decals: {
      classification: 'derived_projection_cache_input',
      stamps: [],
      revision: 0,
      dirty: false,
      dropped: 0
    },
    lighting: {
      classification: 'derived_projection_runtime_stats',
      profileId: 'early_night',
      activeLights: 0,
      droppedLights: 0,
      budgetMax: RENDER_BUDGETS.lightEmitters.maxActive
    },
    napalm: {
      classification: 'derived_projection_runtime_state',
      droplets: [],
      pools: [],
      nextId: 1,
      droppedDroplets: 0,
      droppedPools: 0
    },
    smokeField: {
      classification: 'derived_projection_texture_stats',
      profileId: 'low_night_smoke',
      activeSources: 0,
      contributingLights: 0,
      texturePasses: 0,
      renderMode: 'single_density_texture',
      sourcePolicy: RENDER_BUDGETS.smokeField.sourcePolicy,
      sourceKinds: {},
      droppedSources: 0,
      scatterStrength: 0,
      scatterSourceCount: 0,
      scatterTextureScale: 0,
      scatterPasses: 0,
      scatterBloomPasses: 0,
      scatterPolicy: RENDER_BUDGETS.atmosphericScatter.passPolicy,
      scatterBloomPolicy: RENDER_BUDGETS.atmosphericScatter.bloomPolicy,
      scatterSmoothingPolicy: RENDER_BUDGETS.atmosphericScatter.smoothingPolicy,
      scatterSmoothingPasses: 0
    },
    postProcess: {
      classification: 'derived_projection_post_process_stats',
      enabled: RENDER_BUDGETS.postProcess.enabled,
      policy: RENDER_BUDGETS.postProcess.policy,
      qualityProfile: RENDER_BUDGETS.postProcess.qualityProfile,
      sourcePolicy: RENDER_BUDGETS.postProcess.sourcePolicy,
      bloomPolicy: RENDER_BUDGETS.postProcess.bloomPolicy,
      smoothingPolicy: RENDER_BUDGETS.postProcess.smoothingPolicy,
      exposurePolicy: RENDER_BUDGETS.postProcess.exposurePolicy,
      ditherPolicy: RENDER_BUDGETS.postProcess.ditherPolicy,
      textureScale: RENDER_BUDGETS.postProcess.bloomScale,
      bloomPasses: 0,
      smoothingPasses: 0,
      exposurePasses: 0,
      ditherPasses: 0,
      filterSupported: true
    },
    lightSpaceCulling: {
      classification: 'derived_projection_render_budget_gate_stats',
      enabled: RENDER_BUDGETS.lightSpaceCulling.enabled,
      policy: RENDER_BUDGETS.lightSpaceCulling.policy,
      outsideDetailPolicy: RENDER_BUDGETS.lightSpaceCulling.outsideDetailPolicy,
      actorPolicy: RENDER_BUDGETS.lightSpaceCulling.actorPolicy,
      featherPx: RENDER_BUDGETS.lightSpaceCulling.featherPx,
      softness: RENDER_BUDGETS.lightSpaceCulling.softness,
      activeLights: 0,
      rawRegions: 0,
      mergedRegions: 0,
      coverageRatio: 0,
      featheredCoverageRatio: 0,
      skippedTerrainTiles: 0,
      clippedDecalRegions: 0,
      skippedActors: 0,
      skippedEffects: 0,
      skippedNapalmPools: 0,
      skippedNapalmDroplets: 0,
      culledSmokeSources: 0
    },
    occlusionShadows: {
      classification: 'derived_projection_shadow_runtime_stats',
      enabled: RENDER_BUDGETS.occlusionShadows.enabled,
      blockerPolicy: RENDER_BUDGETS.occlusionShadows.blockerPolicy,
      missingBlockerPolicy: RENDER_BUDGETS.occlusionShadows.missingBlockerPolicy,
      shadowPolicy: RENDER_BUDGETS.occlusionShadows.shadowPolicy,
      lightSpaceClippingPolicy: RENDER_BUDGETS.occlusionShadows.lightSpaceClippingPolicy,
      clippedToLightSpace: true,
      activeBlockers: 0,
      actorShadowBlockers: 0,
      droppedBlockers: 0,
      shadowCastingLights: 0,
      approximateShadowRegions: 0,
      shadowFieldContract: RENDER_BUDGETS.occlusionShadows.shadowFieldContract,
      shadowFieldPacketCount: 0,
      actorShadowFieldPacketCount: 0,
      shadowFieldSampleCount: 0,
      shadowSilhouettePrimitiveCount: 0
    },
    diagnostics: {
      droppedLiveEffects: 0,
      droppedSmokeClouds: 0,
      droppedDecalStamps: 0
    }
  };
}

export function addDecalStamp(renderLayers, stamp) {
  if (!renderLayers?.decals) return null;
  const decals = renderLayers.decals;
  const next = {
    kind: stamp.kind ?? 'generic_decal',
    x: stamp.x,
    y: stamp.y,
    radius: Math.max(0.01, stamp.radius ?? 0.25),
    colour: stamp.colour ?? 'rgba(40,30,24,0.24)',
    opacity: Math.max(0, Math.min(1, stamp.opacity ?? 1)),
    rimColour: stamp.rimColour ?? null,
    softness: Number.isFinite(stamp.softness) ? Math.max(0, Math.min(1, stamp.softness)) : null,
    visualMaterial: stamp.visualMaterial ?? null,
    poolShape: stamp.poolShape ?? null,
    createdAtRevision: decals.revision + 1
  };
  decals.stamps.push(next);
  trimDecalBudget(renderLayers);
  decals.revision += 1;
  decals.dirty = true;
  return next;
}

export function markDecalsClean(renderLayers) {
  if (renderLayers?.decals) renderLayers.decals.dirty = false;
}

export function getRenderLayerStats(renderLayers) {
  return {
    rendererPreferredBackend: renderLayers?.renderer?.preferredBackend ?? RENDER_BUDGETS.renderer.preferredBackend,
    rendererCandidateBackend: renderLayers?.renderer?.candidateBackend ?? RENDER_BUDGETS.renderer.candidateBackend,
    rendererActiveBackend: renderLayers?.renderer?.activeBackend ?? 'unknown',
    rendererBackendStatus: renderLayers?.renderer?.backendStatus ?? 'unknown',
    rendererFallbackReason: renderLayers?.renderer?.fallbackReason ?? null,
    rendererInitializationError: renderLayers?.renderer?.initializationError ?? null,
    rendererWebglContext: renderLayers?.renderer?.webglContext ?? 'unknown',
    rendererTextureUploads: renderLayers?.renderer?.textureUploads ?? 0,
    rendererFullSceneTextureUploadActive: !!renderLayers?.renderer?.fullSceneTextureUploadActive,
    rendererMode: renderLayers?.renderer?.rendererMode ?? 'unknown',
    rendererLegacyCompositeActive: !!renderLayers?.renderer?.legacyCompositeActive,
    rendererPreferenceSource: renderLayers?.renderer?.preferenceSource ?? 'unknown',
    rendererRequestedBackend: renderLayers?.renderer?.requestedBackend ?? RENDER_BUDGETS.renderer.preferredBackend,
    rendererActivationPolicy: renderLayers?.renderer?.activationPolicy ?? RENDER_BUDGETS.renderer.activationPolicy,
    rendererMigrationPolicy: renderLayers?.renderer?.migrationPolicy ?? RENDER_BUDGETS.renderer.migrationPolicy,
    rendererSceneLayerPolicy: renderLayers?.renderer?.sceneLayerPolicy ?? RENDER_BUDGETS.renderer.sceneLayerPolicy,
    unsupportedRendererPolicy: renderLayers?.renderer?.unsupportedRendererPolicy ?? RENDER_BUDGETS.renderer.unsupportedRendererPolicy,
    canvas2dRuntimeAvailable: !!renderLayers?.renderer?.canvas2dRuntimeAvailable,
    hiddenCanvasRenderLoopActive: !!renderLayers?.renderer?.hiddenCanvasRenderLoopActive,
    rendererLayerOrder: [...(renderLayers?.renderer?.layerOrder ?? [])],
    webglLayerOrder: [...(renderLayers?.renderer?.webglLayerOrder ?? [])],
    rendererLayerStats: { ...(renderLayers?.renderer?.layerStats ?? {}) },
    webglMigrationCoverageStatus: renderLayers?.renderer?.webglMigrationCoverageStatus ?? RENDER_BUDGETS.renderer.migrationCoverageStatus,
    webglDarknessLayerActive: !!renderLayers?.renderer?.webglDarknessLayerActive,
    webglLightCount: renderLayers?.renderer?.webglLightCount ?? 0,
    webglDarknessRenderMs: renderLayers?.renderer?.webglDarknessRenderMs ?? 0,
    webglDarknessMode: renderLayers?.renderer?.webglDarknessMode ?? null,
    webglLightingProfileId: renderLayers?.renderer?.webglLightingProfileId ?? null,
    webglLightingInfluenceCount: renderLayers?.renderer?.webglLightingInfluenceCount ?? 0,
    webglFlickeringLightCount: renderLayers?.renderer?.webglFlickeringLightCount ?? 0,
    webglLightSpaceCullingActive: !!renderLayers?.renderer?.webglLightSpaceCullingActive,
    webglLightSpaceCulledCount: renderLayers?.renderer?.webglLightSpaceCulledCount ?? 0,
    webglLightSpaceMode: renderLayers?.renderer?.webglLightSpaceMode ?? null,
    webglOcclusionShadowMode: renderLayers?.renderer?.webglOcclusionShadowMode ?? null,
    webglOcclusionShadowRegions: renderLayers?.renderer?.webglOcclusionShadowRegions ?? 0,
    webglOcclusionShadowRenderable: !!renderLayers?.renderer?.webglOcclusionShadowRenderable,
    webglShadowShaderMode: renderLayers?.renderer?.webglShadowShaderMode ?? null,
    webglShadowCompositeMode: renderLayers?.renderer?.webglShadowCompositeMode ?? null,
    webglShadowBlendStrength: renderLayers?.renderer?.webglShadowBlendStrength ?? 0,
    webglShadowFieldEdgeSoftness: renderLayers?.renderer?.webglShadowFieldEdgeSoftness ?? 0,
    webglShadowFieldPenumbraGamma: renderLayers?.renderer?.webglShadowFieldPenumbraGamma ?? 0,
    webglShadowFieldTailFloor: renderLayers?.renderer?.webglShadowFieldTailFloor ?? 0,
    webglShadowLightHaloBlendScale: renderLayers?.renderer?.webglShadowLightHaloBlendScale ?? 0,
    webglShadowPenumbraTriangleCount: renderLayers?.renderer?.webglShadowPenumbraTriangleCount ?? 0,
    webglShadowCoreTriangleCount: renderLayers?.renderer?.webglShadowCoreTriangleCount ?? 0,
    webglShadowContactTriangleCount: renderLayers?.renderer?.webglShadowContactTriangleCount ?? 0,
    webglShadowSegmentCount: renderLayers?.renderer?.webglShadowSegmentCount ?? 0,
    webglShadowFieldPacketCount: renderLayers?.renderer?.webglShadowFieldPacketCount ?? 0,
    webglShadowFieldSampleCount: renderLayers?.renderer?.webglShadowFieldSampleCount ?? 0,
    webglShadowFieldPrimitiveCount: renderLayers?.renderer?.webglShadowFieldPrimitiveCount ?? 0,
    webglShadowSilhouettePrimitiveCount: renderLayers?.renderer?.webglShadowSilhouettePrimitiveCount ?? 0,
    webglShadowShaderPacketCount: renderLayers?.renderer?.webglShadowShaderPacketCount ?? 0,
    webglShadowShaderPrimitiveCount: renderLayers?.renderer?.webglShadowShaderPrimitiveCount ?? 0,
    webglSceneryLayerActive: !!renderLayers?.renderer?.webglSceneryLayerActive,
    webglSceneryMode: renderLayers?.renderer?.webglSceneryMode ?? null,
    webglScenerySourceCount: renderLayers?.renderer?.webglScenerySourceCount ?? 0,
    webglSceneryPrimitiveCount: renderLayers?.renderer?.webglSceneryPrimitiveCount ?? 0,
    webglSceneryRenderMs: renderLayers?.renderer?.webglSceneryRenderMs ?? 0,
    webglWorldDepthLayerActive: !!renderLayers?.renderer?.webglWorldDepthLayerActive,
    webglWorldDepthMode: renderLayers?.renderer?.webglWorldDepthMode ?? null,
    webglWorldDepthItemCount: renderLayers?.renderer?.webglWorldDepthItemCount ?? 0,
    webglDecalLayerActive: !!renderLayers?.renderer?.webglDecalLayerActive,
    webglDecalMode: renderLayers?.renderer?.webglDecalMode ?? null,
    webglDecalSourceCount: renderLayers?.renderer?.webglDecalSourceCount ?? 0,
    webglDecalPrimitiveCount: renderLayers?.renderer?.webglDecalPrimitiveCount ?? 0,
    webglDecalRenderMs: renderLayers?.renderer?.webglDecalRenderMs ?? 0,
    webglEffectLayerActive: !!renderLayers?.renderer?.webglEffectLayerActive,
    webglEffectMode: renderLayers?.renderer?.webglEffectMode ?? null,
    webglEffectSourceCount: renderLayers?.renderer?.webglEffectSourceCount ?? 0,
    webglEffectPrimitiveCount: renderLayers?.renderer?.webglEffectPrimitiveCount ?? 0,
    webglEffectRenderMs: renderLayers?.renderer?.webglEffectRenderMs ?? 0,
    webglParticleCount: renderLayers?.renderer?.webglParticleCount ?? 0,
    webglParticlePrimitiveCount: renderLayers?.renderer?.webglParticlePrimitiveCount ?? 0,
    webglParticleBudgetMax: renderLayers?.renderer?.webglParticleBudgetMax ?? 0,
    webglHudLayerActive: !!renderLayers?.renderer?.webglHudLayerActive,
    webglHudLineCount: renderLayers?.renderer?.webglHudLineCount ?? 0,
    webglHudRenderMs: renderLayers?.renderer?.webglHudRenderMs ?? 0,
    webglHudMode: renderLayers?.renderer?.webglHudMode ?? null,
    webglPlayerWyvernSilhouetteActive: !!renderLayers?.renderer?.webglPlayerWyvernSilhouetteActive,
    webglPlayerWyvernPartCount: renderLayers?.renderer?.webglPlayerWyvernPartCount ?? 0,
    webglRaiderHumanoidSilhouetteActive: !!renderLayers?.renderer?.webglRaiderHumanoidSilhouetteActive,
    webglRaiderHumanoidPartCount: renderLayers?.renderer?.webglRaiderHumanoidPartCount ?? 0,
    webglRaiderHumanoidTorchSocketCount: renderLayers?.renderer?.webglRaiderHumanoidTorchSocketCount ?? 0,
    webglRaiderHumanoidSpearSocketCount: renderLayers?.renderer?.webglRaiderHumanoidSpearSocketCount ?? 0,
    webglRaiderHumanoidMode: renderLayers?.renderer?.webglRaiderHumanoidMode ?? null,
    webglPredatorSilhouetteActive: !!renderLayers?.renderer?.webglPredatorSilhouetteActive,
    webglPredatorPartCount: renderLayers?.renderer?.webglPredatorPartCount ?? 0,
    webglPredatorMode: renderLayers?.renderer?.webglPredatorMode ?? null,
    webglActorRenderMs: renderLayers?.renderer?.webglActorRenderMs ?? 0,
    webglActorMode: renderLayers?.renderer?.webglActorMode ?? null,
    webglActorShadowLodMode: renderLayers?.renderer?.webglActorShadowLodMode ?? null,
    webglActorShadowLodCount: renderLayers?.renderer?.webglActorShadowLodCount ?? 0,
    webglActorShadowLodPrimitiveCount: renderLayers?.renderer?.webglActorShadowLodPrimitiveCount ?? 0,
    webglPostProcessActive: !!renderLayers?.renderer?.webglPostProcessActive,
    webglPostProcessMode: renderLayers?.renderer?.webglPostProcessMode ?? null,
    webglPostProcessRenderMs: renderLayers?.renderer?.webglPostProcessRenderMs ?? 0,
    webglPostProcessPassCount: renderLayers?.renderer?.webglPostProcessPassCount ?? 0,
    webglPostProcessRenderTargetActive: !!renderLayers?.renderer?.webglPostProcessRenderTargetActive,
    webglFogSmokeLayerActive: !!renderLayers?.renderer?.webglFogSmokeLayerActive,
    webglFogSmokeMode: renderLayers?.renderer?.webglFogSmokeMode ?? null,
    webglFogSmokeSourceCount: renderLayers?.renderer?.webglFogSmokeSourceCount ?? 0,
    webglFogSmokePrimitiveCount: renderLayers?.renderer?.webglFogSmokePrimitiveCount ?? 0,
    webglFogSmokeRenderMs: renderLayers?.renderer?.webglFogSmokeRenderMs ?? 0,
    rendererBackendPresentMs: renderLayers?.renderer?.backendPresentMs ?? 0,
    rendererTotalRenderMs: renderLayers?.renderer?.totalRenderMs ?? 0,
    terrainCachePolicy: renderLayers?.terrain?.cachePolicy ?? RENDER_BUDGETS.renderer.terrainCachePolicy,
    terrainCacheMode: renderLayers?.terrain?.cacheMode ?? 'unknown',
    terrainCacheMapKey: renderLayers?.terrain?.mapKey ?? '',
    terrainCacheRebuilds: renderLayers?.terrain?.cacheRebuilds ?? 0,
    terrainFullMapTiles: renderLayers?.terrain?.fullMapTiles ?? 0,
    terrainVisibleTilesConsidered: renderLayers?.terrain?.visibleTilesConsidered ?? 0,
    terrainVisibleTilesDrawn: renderLayers?.terrain?.visibleTilesDrawn ?? 0,
    terrainVisibleTileColumns: renderLayers?.terrain?.visibleTileColumns ?? 0,
    terrainVisibleTileRows: renderLayers?.terrain?.visibleTileRows ?? 0,
    renderTimingPolicy: renderLayers?.frameTiming?.policy ?? 'renderer_phase_timing_ms',
    renderTimingFrame: renderLayers?.frameTiming?.frame ?? 0,
    renderTotalMs: renderLayers?.frameTiming?.totalMs ?? 0,
    renderBackendBeginMs: renderLayers?.frameTiming?.backendBeginMs ?? 0,
    renderLightSpaceMs: renderLayers?.frameTiming?.lightSpaceMs ?? 0,
    renderTerrainMs: renderLayers?.frameTiming?.terrainMs ?? 0,
    renderWorldDetailsMs: renderLayers?.frameTiming?.worldDetailsMs ?? 0,
    renderLightingMs: renderLayers?.frameTiming?.lightingMs ?? 0,
    renderSmokeMs: renderLayers?.frameTiming?.smokeMs ?? 0,
    renderPostProcessMs: renderLayers?.frameTiming?.postProcessMs ?? 0,
    renderHudMs: renderLayers?.frameTiming?.hudMs ?? 0,
    renderBackendPresentMs: renderLayers?.frameTiming?.backendPresentMs ?? 0,
    decalStamps: renderLayers?.decals?.stamps.length ?? 0,
    decalRevision: renderLayers?.decals?.revision ?? 0,
    decalDirty: !!renderLayers?.decals?.dirty,
    activeLights: renderLayers?.lighting?.activeLights ?? 0,
    lightBudgetMax: renderLayers?.lighting?.budgetMax ?? RENDER_BUDGETS.lightEmitters.maxActive,
    droppedLights: renderLayers?.lighting?.droppedLights ?? 0,
    lightingProfileId: renderLayers?.lighting?.profileId ?? 'unknown',
    napalmDroplets: renderLayers?.napalm?.droplets.length ?? 0,
    napalmPools: renderLayers?.napalm?.pools.length ?? 0,
    droppedNapalmDroplets: renderLayers?.napalm?.droppedDroplets ?? 0,
    droppedNapalmPools: renderLayers?.napalm?.droppedPools ?? 0,
    smokeFieldActiveSources: renderLayers?.smokeField?.activeSources ?? 0,
    smokeFieldContributingLights: renderLayers?.smokeField?.contributingLights ?? 0,
    smokeFieldTexturePasses: renderLayers?.smokeField?.texturePasses ?? 0,
    smokeFieldMode: renderLayers?.smokeField?.renderMode ?? 'none',
    smokeFieldSourcePolicy: renderLayers?.smokeField?.sourcePolicy ?? 'none',
    smokeFieldSourceKinds: { ...(renderLayers?.smokeField?.sourceKinds ?? {}) },
    droppedSmokeFieldSources: renderLayers?.smokeField?.droppedSources ?? 0,
    atmosphericScatterStrength: renderLayers?.smokeField?.scatterStrength ?? 0,
    atmosphericScatterSourceCount: renderLayers?.smokeField?.scatterSourceCount ?? 0,
    atmosphericScatterTextureScale: renderLayers?.smokeField?.scatterTextureScale ?? 0,
    atmosphericScatterPasses: renderLayers?.smokeField?.scatterPasses ?? 0,
    atmosphericScatterBloomPasses: renderLayers?.smokeField?.scatterBloomPasses ?? 0,
    atmosphericScatterPolicy: renderLayers?.smokeField?.scatterPolicy ?? RENDER_BUDGETS.atmosphericScatter.passPolicy,
    atmosphericScatterBloomPolicy: renderLayers?.smokeField?.scatterBloomPolicy ?? RENDER_BUDGETS.atmosphericScatter.bloomPolicy,
    atmosphericScatterSmoothingPolicy: renderLayers?.smokeField?.scatterSmoothingPolicy ?? RENDER_BUDGETS.atmosphericScatter.smoothingPolicy,
    atmosphericScatterSmoothingPasses: renderLayers?.smokeField?.scatterSmoothingPasses ?? 0,
    postProcessEnabled: renderLayers?.postProcess?.enabled ?? RENDER_BUDGETS.postProcess.enabled,
    postProcessPolicy: renderLayers?.postProcess?.policy ?? RENDER_BUDGETS.postProcess.policy,
    postProcessQualityProfile: renderLayers?.postProcess?.qualityProfile ?? RENDER_BUDGETS.postProcess.qualityProfile,
    postProcessSourcePolicy: renderLayers?.postProcess?.sourcePolicy ?? RENDER_BUDGETS.postProcess.sourcePolicy,
    postProcessBloomPolicy: renderLayers?.postProcess?.bloomPolicy ?? RENDER_BUDGETS.postProcess.bloomPolicy,
    postProcessSmoothingPolicy: renderLayers?.postProcess?.smoothingPolicy ?? RENDER_BUDGETS.postProcess.smoothingPolicy,
    postProcessExposurePolicy: renderLayers?.postProcess?.exposurePolicy ?? RENDER_BUDGETS.postProcess.exposurePolicy,
    postProcessDitherPolicy: renderLayers?.postProcess?.ditherPolicy ?? RENDER_BUDGETS.postProcess.ditherPolicy,
    postProcessTextureScale: renderLayers?.postProcess?.textureScale ?? RENDER_BUDGETS.postProcess.bloomScale,
    postProcessBloomPasses: renderLayers?.postProcess?.bloomPasses ?? 0,
    postProcessSmoothingPasses: renderLayers?.postProcess?.smoothingPasses ?? 0,
    postProcessExposurePasses: renderLayers?.postProcess?.exposurePasses ?? 0,
    postProcessDitherPasses: renderLayers?.postProcess?.ditherPasses ?? 0,
    postProcessFilterSupported: renderLayers?.postProcess?.filterSupported ?? true,
    lightSpaceCullingEnabled: renderLayers?.lightSpaceCulling?.enabled ?? RENDER_BUDGETS.lightSpaceCulling.enabled,
    lightSpaceCullingPolicy: renderLayers?.lightSpaceCulling?.policy ?? RENDER_BUDGETS.lightSpaceCulling.policy,
    lightSpaceOutsideDetailPolicy: renderLayers?.lightSpaceCulling?.outsideDetailPolicy ?? RENDER_BUDGETS.lightSpaceCulling.outsideDetailPolicy,
    lightSpaceActorPolicy: renderLayers?.lightSpaceCulling?.actorPolicy ?? RENDER_BUDGETS.lightSpaceCulling.actorPolicy,
    lightSpaceFeatherPx: renderLayers?.lightSpaceCulling?.featherPx ?? RENDER_BUDGETS.lightSpaceCulling.featherPx,
    lightSpaceSoftness: renderLayers?.lightSpaceCulling?.softness ?? RENDER_BUDGETS.lightSpaceCulling.softness,
    lightSpaceActiveLights: renderLayers?.lightSpaceCulling?.activeLights ?? 0,
    lightSpaceRawRegions: renderLayers?.lightSpaceCulling?.rawRegions ?? 0,
    lightSpaceMergedRegions: renderLayers?.lightSpaceCulling?.mergedRegions ?? 0,
    lightSpaceCoverageRatio: renderLayers?.lightSpaceCulling?.coverageRatio ?? 0,
    lightSpaceFeatheredCoverageRatio: renderLayers?.lightSpaceCulling?.featheredCoverageRatio ?? 0,
    skippedTerrainTilesOutsideLight: renderLayers?.lightSpaceCulling?.skippedTerrainTiles ?? 0,
    clippedDecalLightRegions: renderLayers?.lightSpaceCulling?.clippedDecalRegions ?? 0,
    skippedActorsOutsideLight: renderLayers?.lightSpaceCulling?.skippedActors ?? 0,
    skippedEffectsOutsideLight: renderLayers?.lightSpaceCulling?.skippedEffects ?? 0,
    skippedNapalmPoolsOutsideLight: renderLayers?.lightSpaceCulling?.skippedNapalmPools ?? 0,
    skippedNapalmDropletsOutsideLight: renderLayers?.lightSpaceCulling?.skippedNapalmDroplets ?? 0,
    culledSmokeSourcesOutsideLight: renderLayers?.lightSpaceCulling?.culledSmokeSources ?? 0,
    occlusionShadowEnabled: renderLayers?.occlusionShadows?.enabled ?? RENDER_BUDGETS.occlusionShadows.enabled,
    occlusionBlockerPolicy: renderLayers?.occlusionShadows?.blockerPolicy ?? RENDER_BUDGETS.occlusionShadows.blockerPolicy,
    occlusionMissingBlockerPolicy: renderLayers?.occlusionShadows?.missingBlockerPolicy ?? RENDER_BUDGETS.occlusionShadows.missingBlockerPolicy,
    occlusionShadowPolicy: renderLayers?.occlusionShadows?.shadowPolicy ?? RENDER_BUDGETS.occlusionShadows.shadowPolicy,
    occlusionShadowClippingPolicy: renderLayers?.occlusionShadows?.lightSpaceClippingPolicy ?? RENDER_BUDGETS.occlusionShadows.lightSpaceClippingPolicy,
    occlusionShadowsClippedToLightSpace: renderLayers?.occlusionShadows?.clippedToLightSpace ?? true,
    activeOcclusionBlockers: renderLayers?.occlusionShadows?.activeBlockers ?? 0,
    activeActorShadowBlockers: renderLayers?.occlusionShadows?.actorShadowBlockers ?? 0,
    droppedOcclusionBlockers: renderLayers?.occlusionShadows?.droppedBlockers ?? 0,
    shadowCastingLights: renderLayers?.occlusionShadows?.shadowCastingLights ?? 0,
    approximateShadowRegions: renderLayers?.occlusionShadows?.approximateShadowRegions ?? 0,
    occlusionShadowFieldContract: renderLayers?.occlusionShadows?.shadowFieldContract ?? RENDER_BUDGETS.occlusionShadows.shadowFieldContract,
    occlusionShadowFieldPacketCount: renderLayers?.occlusionShadows?.shadowFieldPacketCount ?? 0,
    occlusionActorShadowFieldPacketCount: renderLayers?.occlusionShadows?.actorShadowFieldPacketCount ?? 0,
    occlusionShadowFieldSampleCount: renderLayers?.occlusionShadows?.shadowFieldSampleCount ?? 0,
    occlusionShadowSilhouettePrimitiveCount: renderLayers?.occlusionShadows?.shadowSilhouettePrimitiveCount ?? 0,
    droppedLiveEffects: renderLayers?.diagnostics?.droppedLiveEffects ?? 0,
    droppedSmokeClouds: renderLayers?.diagnostics?.droppedSmokeClouds ?? 0,
    droppedDecalStamps: renderLayers?.diagnostics?.droppedDecalStamps ?? 0
  };
}

function trimDecalBudget(renderLayers) {
  const max = RENDER_BUDGETS.decalStamps.maxActive;
  const decals = renderLayers.decals;
  if (decals.stamps.length <= max) return;
  const dropCount = decals.stamps.length - max;
  decals.stamps.splice(0, dropCount);
  decals.dropped += dropCount;
  renderLayers.diagnostics.droppedDecalStamps += dropCount;
}
