import assert from 'node:assert/strict';
import path from 'node:path';

import { loadModuleCopy } from './helpers/browser-module-loader.mjs';

export default async function runQaEvidenceProvenanceTests() {
  const modulePath = path.resolve(process.cwd(), 'public', 'spatial', 'qaEvidenceProvenance.js');
  const { normalizeQAEvidenceProvenance } = await loadModuleCopy(modulePath, { label: 'qaEvidenceProvenance' });

  const governed = normalizeQAEvidenceProvenance({
    kind: 'browser-run',
    label: 'Latest browser run',
    sourcePath: 'data/spatial/qa/qa_123.json',
    sourceClass: 'live_canonical',
    freshnessClass: 'live_canonical',
    observedAt: '2026-04-08T12:34:00.000Z',
    generatedBy: {
      system: 'ui',
      module: 'qaRunner.runQARun',
    },
  });

  assert.equal(governed.hasProvenance, true);
  assert.equal(governed.sourcePath, 'data/spatial/qa/qa_123.json');
  assert.equal(governed.sourceLabel, 'Latest browser run');
  assert.equal(governed.classification, 'browser-run');
  assert.equal(governed.freshness, 'Live canonical');
  assert.equal(governed.generatedAt, '2026-04-08T12:34:00.000Z');
  assert.equal(governed.observedAt, '2026-04-08T12:34:00.000Z');
  assert.equal(governed.chips.some((chip) => chip.label === 'Source' && chip.value === 'data/spatial/qa/qa_123.json'), true);
  assert.equal(governed.chips.some((chip) => chip.label === 'Freshness' && chip.value === 'Live canonical'), true);
  assert.equal(governed.chips.some((chip) => chip.label === 'Generated by' && chip.value === 'ui | qaRunner.runQARun'), true);

  const derived = normalizeQAEvidenceProvenance({
    kind: 'studio-boot',
    sourcePath: 'data/spatial/qa/local-gates/studio_boot.json',
    sourceClass: 'derived_current',
    freshnessClass: 'derived_current',
    fallbackUsed: true,
  });

  assert.equal(derived.hasProvenance, true);
  assert.equal(derived.chips.some((chip) => chip.label === 'Fallback' && chip.value === 'yes'), true);
  assert.equal(derived.chips.some((chip) => chip.label === 'Freshness' && chip.value === 'Derived current'), true);

  const absent = normalizeQAEvidenceProvenance({});
  assert.equal(absent.hasProvenance, false);
  assert.equal(absent.chips.length, 0);
}
