import assert from 'node:assert/strict';
import path from 'node:path';

import { loadModuleCopy } from './helpers/browser-module-loader.mjs';

export default async function runQaStructuredProvenanceTests() {
  const modulePath = path.resolve(process.cwd(), 'public', 'spatial', 'qaEvidenceProvenance.js');
  const {
    buildQAEvidenceProvenancePresentation,
    normalizeQAEvidenceProvenance,
  } = await loadModuleCopy(modulePath, { label: 'qaEvidenceProvenance' });

  const governedTrace = {
    kind: 'structured-report',
    domain: 'qa',
    projectionId: 'qa-structured-report',
    sourcePath: 'data/spatial/qa/structured/latest.json',
    sourceClass: 'projection',
    freshnessClass: 'live_canonical',
    generatedAt: '2026-04-08T12:00:00.000Z',
    observedAt: '2026-04-08T12:15:00.000Z',
    fallbackUsed: false,
    generatedBy: {
      system: 'qa',
      module: 'structuredQa.buildReport',
    },
    derivedFrom: 'data/spatial/qa/browser/latest.json',
  };

  const presentation = buildQAEvidenceProvenancePresentation(governedTrace, { fallbackLabel: 'Derived summary' });
  assert.equal(presentation.hasRenderableProvenance, true);
  assert.equal(presentation.fallbackLabel, '');
  assert.equal(presentation.chips.some((chip) => chip.label === 'Domain' && chip.value === 'qa'), true);
  assert.equal(presentation.chips.some((chip) => chip.label === 'Projection' && chip.value === 'qa-structured-report'), true);
  assert.equal(presentation.chips.some((chip) => chip.label === 'Freshness' && chip.value === 'Live canonical'), true);
  assert.equal(presentation.chips.some((chip) => chip.label === 'Generated by' && chip.value === 'qa | structuredQa.buildReport'), true);
  assert.equal(presentation.chips.some((chip) => chip.label === 'Derived from' && chip.value === 'data/spatial/qa/browser/latest.json'), true);

  const normalized = normalizeQAEvidenceProvenance(governedTrace);
  assert.equal(normalized.hasProvenance, true);
  assert.equal(normalized.sourceLabel, 'structured-report');

  const fallbackPresentation = buildQAEvidenceProvenancePresentation({}, { fallbackLabel: 'Derived summary' });
  assert.equal(fallbackPresentation.hasRenderableProvenance, false);
  assert.equal(fallbackPresentation.fallbackLabel, 'Derived summary');
  assert.equal(fallbackPresentation.chips.length, 0);
}
