export function buildEnemyBehaviourText(ai) {
  return {
    state: ai.state,
    targetId: ai.targetId,
    anchorX: Number(ai.anchorX.toFixed(2)),
    anchorY: Number(ai.anchorY.toFixed(2)),
    roamRadius: ai.roamRadius,
    aggroRange: ai.aggroRange,
    attackRange: ai.attackRange,
    attackProfileIds: [...(ai.attackProfileIds ?? [])],
    activeAttackProfileId: ai.activeAttackProfileId ?? null,
    attackPhase: ai.attackPhase ?? 'idle',
    attackTimer: Number((ai.attackTimer ?? 0).toFixed(3)),
    attackDamageApplied: ai.attackDamageApplied === true,
    cooldownTimer: Number((ai.cooldownTimer ?? 0).toFixed(3)),
    pendingAttackTargetId: ai.pendingAttackTargetId ?? null,
    lastAttackAt: ai.lastAttackAt == null ? null : Number(ai.lastAttackAt.toFixed(3)),
    lastAttackProfileId: ai.lastAttackProfileId ?? null,
    lastAttackHitIds: [...(ai.lastAttackHitIds ?? [])],
    smokeSearch: {
      active: ai.state === 'search',
      timer: Number((ai.smokeSearchTimer ?? 0).toFixed(3)),
      reacquireTimer: Number((ai.smokeReacquireTimer ?? 0).toFixed(3)),
      centerX: ai.smokeSearchCenterX == null ? null : Number(ai.smokeSearchCenterX.toFixed(2)),
      centerY: ai.smokeSearchCenterY == null ? null : Number(ai.smokeSearchCenterY.toFixed(2)),
      targetX: ai.smokeSearchTargetX == null ? null : Number(ai.smokeSearchTargetX.toFixed(2)),
      targetY: ai.smokeSearchTargetY == null ? null : Number(ai.smokeSearchTargetY.toFixed(2)),
      breakCount: ai.smokeBreakCount ?? 0,
      lastBreakAt: ai.lastSmokeBreakAt == null ? null : Number(ai.lastSmokeBreakAt.toFixed(3)),
      lastBreakReason: ai.lastSmokeBreakReason ?? null,
      lastSourceKind: ai.lastSmokeSourceKind ?? null
    },
    engagementTargetX: ai.engagementTargetX == null ? null : Number(ai.engagementTargetX.toFixed(2)),
    engagementTargetY: ai.engagementTargetY == null ? null : Number(ai.engagementTargetY.toFixed(2)),
    engagementSlotAngle: ai.engagementSlotAngle == null ? null : Number(ai.engagementSlotAngle.toFixed(3)),
    engagementDistance: ai.engagementDistance == null ? null : Number(ai.engagementDistance.toFixed(3)),
    lastSteeringAngleDegrees: ai.lastSteeringAngleDegrees ?? 0,
    usedObstacleSteering: ai.usedObstacleSteering === true,
    usedStuckRecovery: ai.usedStuckRecovery === true,
    movementBlocked: ai.movementBlocked === true,
    steeringSuccessCount: ai.steeringSuccessCount ?? 0,
    blockedMoveCount: ai.blockedMoveCount ?? 0,
    guard: {
      enabled: ai.guardEnabled === true,
      holdTimer: Number((ai.guardHoldTimer ?? 0).toFixed(3)),
      cooldownTimer: Number((ai.guardCooldownTimer ?? 0).toFixed(3)),
      recoveryTimer: Number((ai.guardRecoveryTimer ?? 0).toFixed(3)),
      protectedArcRadians: Number((ai.guardProtectedArcRadians ?? 0).toFixed(3)),
      damageMultiplier: Number((ai.guardDamageMultiplier ?? 1).toFixed(3)),
      holdCount: ai.guardHoldCount ?? 0,
      blockedCount: ai.guardBlockedCount ?? 0,
      lastAttackerId: ai.guardLastAttackerId ?? null,
      lastDamageBefore: ai.guardLastDamageBefore,
      lastDamageAfter: ai.guardLastDamageAfter,
      lastReason: ai.guardLastReason ?? null
    },
    failedMoveCount: ai.failedMoveCount ?? 0,
    timeSinceMeaningfulProgress: Number((ai.timeSinceMeaningfulProgress ?? 0).toFixed(3)),
    currentUnstickMode: ai.currentUnstickMode ?? null,
    unstickCooldown: Number((ai.unstickCooldown ?? 0).toFixed(3)),
    stuckRecoveryCount: ai.stuckRecoveryCount ?? 0,
    stuckRetreatCount: ai.stuckRetreatCount ?? 0,
    repathPauseTimer: Number((ai.repathPauseTimer ?? 0).toFixed(3)),
    hazardAvoidanceCount: ai.hazardAvoidanceCount ?? 0,
    lastHazardAvoided: ai.lastHazardAvoided ?? null,
    lastProgressDelta: Number((ai.lastProgressDelta ?? 0).toFixed(3)),
    leashRange: ai.leashRange,
    roamTargetX: Number(ai.roamTargetX.toFixed(2)),
    roamTargetY: Number(ai.roamTargetY.toFixed(2)),
    decisionCooldown: Number(ai.decisionCooldown.toFixed(3)),
    decisionInterval: ai.decisionInterval,
    lastStateChangeAt: Number(ai.lastStateChangeAt.toFixed(3))
  };
}
