import { assert, equal } from './assert.mjs';
import { ACTION_SYSTEM_NAMES } from '../src/game/systemOrder.js';
import { validateWorldState } from '../src/debug/validation.js';
import { createDebugSnapshot } from '../src/debug/snapshot.js';
import { createDemoMap } from '../src/world/map.js';
import { createInitialGameState } from '../src/game/state.js';
import { ScenarioId, getScenario } from '../src/data/scenarios.js';
import { ACTORS } from '../src/data/actors.js';
import { EntityKind } from '../src/constants/entityKinds.js';
import { CreatureRecipeId, getCreatureRecipe } from '../src/data/creatures/creatureRecipes.js';

const map = createDemoMap();
const game = createInitialGameState(map);
const validation = validateWorldState(game.world);
assert(validation.ok, `ECS world should validate: ${validation.errors.join(',')}`);
const snapshot = createDebugSnapshot(game);
equal(snapshot.systemOrder[0], 'timerSystem', 'timers should tick before input/actions');
equal(snapshot.systemOrder.at(-1), 'viewSyncSystem', 'views should sync after gameplay systems');
assert(ACTION_SYSTEM_NAMES.includes('healthSystem'), 'health system seam should be explicit');
assert(ACTION_SYSTEM_NAMES.includes('deathLifecycleSystem'), 'death aftermath should remain an explicit ECS system');
assert(ACTION_SYSTEM_NAMES.includes('scenarioSystem'), 'scenario system should be explicit');
assert(ACTION_SYSTEM_NAMES.includes('actorSeparationSystem'), 'actor separation should remain an explicit ECS system');
assert(ACTION_SYSTEM_NAMES.indexOf('enemyPressureSystem') < ACTION_SYSTEM_NAMES.indexOf('actorSeparationSystem'), 'separation should run after enemy movement intent');
assert(ACTION_SYSTEM_NAMES.indexOf('actorSeparationSystem') < ACTION_SYSTEM_NAMES.indexOf('enemyAttackSystem'), 'attack hits should resolve from post-separation positions');
assert(ACTION_SYSTEM_NAMES.indexOf('wyvernAttackContactSystem') < ACTION_SYSTEM_NAMES.indexOf('deathLifecycleSystem'), 'death lifecycle should consume deaths after attack contact resolution');
assert(ACTION_SYSTEM_NAMES.indexOf('deathLifecycleSystem') < ACTION_SYSTEM_NAMES.indexOf('unitSpawnerSystem'), 'spawners should recover live capacity after death cleanup');
equal(getScenario(ScenarioId.FIRST_ESCAPE).enemySpawns.length, 5, 'scenario data should own enemy spawn list');
equal(getScenario(ScenarioId.FIRST_ESCAPE).sceneObjects.length, 22, 'scenario data should own the broadened forest-plus-raid-emitter scene object list');
equal(ACTORS[EntityKind.RAIDER].defaultCreatureRecipeId, CreatureRecipeId.RAIDER_SCAVENGER, 'actor identity should point at canonical raider recipe truth');
assert(getCreatureRecipe(CreatureRecipeId.RAIDER_SCAVENGER).behaviour.parameters.attackRange > 0, 'raider AI tuning should live in creature recipe data');
assert(map.blobMasks.water.length > 0, 'terrain masks should include painted water runs');
equal(map.sceneObjects.length, 22, 'map should instantiate explicit scene objects from scenario data');
