import { readFile } from 'node:fs/promises';
import * as THREE from 'three';
import { assert, equal } from './assert.mjs';
import { CONFIG } from '../src/config.js';
import { createInitialGameState } from '../src/game/createGame.js';
import { syncGameViews } from '../src/game/selectors.js';
import { createRenderProjection3DCompiler } from '../src/projection/renderProjection3D.js';
import { createCamera } from '../src/render/camera.js';
import { PROCEDURAL_WYVERN_MESH_RECIPE_CONTRACT, ThreeWyvernMesh } from '../src/render/backends/three/ThreeWyvernMesh.js';
import { wyvernProjectionSystem } from '../src/systems/wyvernProjectionSystem.js';
import { bodyContactRigSystem } from '../src/systems/bodyContactRigSystem.js';
import { createDemoMap } from '../src/world/map.js';

const map = createDemoMap();
const game = createInitialGameState(map);
wyvernProjectionSystem({ game, dt: 1 / 60 });
bodyContactRigSystem({ game });
syncGameViews(game);
const compiler = createRenderProjection3DCompiler(CONFIG);
const projection = compiler.compile({ time: 0, map, game, camera: createCamera({ clientWidth: 1280, clientHeight: 720 }, map) });
const actor = projection.dynamicWorld.actors.find((entry) => entry.team === 'player');
const root = new THREE.Group();
const mesh = new ThreeWyvernMesh(root, actor);
mesh.update(actor);
const diagnostics = mesh.diagnostics();
const rendererSource = await readFile(new URL('../src/render/backends/three/ThreeWyvernMesh.js', import.meta.url), 'utf8');

equal(mesh.group.userData.contract, PROCEDURAL_WYVERN_MESH_RECIPE_CONTRACT, 'wyvern mesh should publish the procedural recipe contract');
assert(!rendererSource.includes('GLTFLoader'), 'production player embodiment must not import a GLTF loader');
assert(!rendererSource.includes('dragon_main_march_v5_baby_rig'), 'rejected baby rig asset must remain outside the production player graph');
assert(!rendererSource.includes('SkinnedMesh'), 'production player embodiment must remain procedural until a replacement clears comparative visual acceptance');
assert(diagnostics.meshCount >= 35, 'faceted wyvern should include cohesive masses, articulated limbs, digits, tail, eyes, and claws');
equal(diagnostics.membraneCount, 2, 'faceted wyvern should render both wing membranes');
equal(diagnostics.clawCount, 10, 'hatchling should have three grounded toes and two wing talons per side');
equal(diagnostics.hornCount, 2, 'hatchling silhouette should include paired head hornlets');
equal(diagnostics.dorsalSpineCount, 7, 'hatchling silhouette should carry a tapered dorsal spine line into the tail');
equal(diagnostics.silhouettePlateCount, 4, 'shoulders and haunches should remain readable as paired silhouette masses');
assert(diagnostics.detailInstanceCount >= 23, 'anatomical detail should remain batched as reusable instances');
equal(mesh.group.userData.bodyContactRig, actor.bodyContactRig, 'rendered mesh should expose the same projected contact rig without creating gameplay truth');
const membranes = [];
mesh.group.traverse((object) => { if (object.name?.includes('membrane')) membranes.push(object); });
assert(membranes.every((entry) => entry.geometry.getAttribute('position').array.some((value) => Math.abs(value) > 0.001)), 'membrane vertices should follow solved rig points');
const topologyIds = Object.values(mesh.geometries).map((geometry) => geometry.uuid);
assert(Object.values(mesh.geometries).every((geometry) => geometry.getAttribute('color')?.count === geometry.getAttribute('position')?.count), 'every reusable wyvern geometry should carry deterministic per-facet tones');
mesh.update(actor);
equal(mesh.diagnostics().topologyBuilds, 1, 'pose updates must not rebuild wyvern topology');
equal(Object.values(mesh.geometries).map((geometry) => geometry.uuid).join(':'), topologyIds.join(':'), 'pose updates should retain every reusable geometry');
mesh.dispose();
compiler.dispose();
